import Foundation

/// Verdict rendu sur une copie, avant toute lecture de son contenu.
///
/// La raison du refus n'est jamais montrée à l'utilisateur telle quelle : elle sert au
/// diagnostic (journal, tests, support). D'où l'exigence qu'elle reste exacte même quand
/// plusieurs raisons s'appliquent simultanément.
public enum PrivacyDecision: Equatable, Sendable {
    /// La copie peut être lue puis enregistrée.
    case allow
    /// Contenu marqué confidentiel par l'application source (mot de passe, jeton).
    case rejectedConcealed
    /// Presse-papiers transitoire ou auto-généré : non destiné à l'historique.
    case rejectedTransient
    /// L'application source figure dans la liste d'exclusion de l'utilisateur.
    case rejectedExcludedApp
    /// Capture suspendue par l'utilisateur.
    case rejectedPaused
}

/// Filtre de confidentialité : décide si une copie a le droit d'être enregistrée (FR-9,
/// FR-10, FR-11).
///
/// La décision se prend sur les seuls **identifiants de types** annoncés par le
/// presse-papiers et sur l'application source — jamais sur le contenu. C'est la garantie qui
/// tient la promesse du produit : un mot de passe n'est pas *filtré après lecture*, il n'est
/// tout simplement jamais lu.
///
/// Le type ne dépend pas d'AppKit et n'a pas d'état : les identifiants de types transitent en
/// `String` bruts, ce qui le rend testable sans presse-papiers réel.
public struct PrivacyGate: Sendable {
    // MARK: Types surveillés

    /// Types signalant un contenu confidentiel.
    ///
    /// `org.nspasteboard.ConcealedType` vient de la convention de nspasteboard.com : un
    /// gestionnaire de mots de passe l'ajoute au presse-papiers pour demander aux
    /// gestionnaires d'historique de ne rien conserver. `com.agilebits.onepassword` est le
    /// marqueur propriétaire que 1Password posait avant l'adoption de cette convention ;
    /// il reste surveillé pour couvrir les versions anciennes.
    public static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "com.agilebits.onepassword",
    ]

    /// Types signalant un presse-papiers de passage, également issus de la convention
    /// nspasteboard.com : `TransientType` pour un contenu éphémère (aperçu, glisser-déposer
    /// interne), `AutoGeneratedType` pour un contenu produit par une machine et non par un
    /// geste de copie de l'utilisateur.
    public static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// Tous les types qui provoquent un rejet, quel que soit le réglage.
    ///
    /// Aucune préférence ne permet de les accepter : c'est délibéré et non négociable (FR-9).
    public static let alwaysRejectedTypes: Set<String> =
        concealedTypes.union(transientTypes)

    public init() {}

    // MARK: Décision

    /// Rend le verdict pour une copie.
    ///
    /// Les raisons sont examinées dans l'ordre confidentiel > transitoire > application
    /// exclue > pause : la plus grave d'abord, pour qu'un diagnostic ne masque jamais un
    /// marqueur de confidentialité derrière une raison anodine.
    ///
    /// - Parameters:
    ///   - availableTypes: identifiants de types annoncés par le presse-papiers, tels quels.
    ///   - sourceBundleIdentifier: identifiant de bundle de l'application source, `nil` si
    ///     macOS ne l'expose pas — auquel cas aucune exclusion ne peut s'appliquer.
    ///   - captureEnabled: `false` quand l'utilisateur a suspendu la capture.
    ///   - excludedBundleIdentifiers: liste d'exclusion de l'utilisateur.
    public func decide(
        availableTypes: [String],
        sourceBundleIdentifier: String?,
        captureEnabled: Bool,
        excludedBundleIdentifiers: [String]
    ) -> PrivacyDecision {
        // Les types arrivent du système sous leur forme canonique : comparaison exacte.
        if availableTypes.contains(where: Self.concealedTypes.contains) {
            return .rejectedConcealed
        }
        if availableTypes.contains(where: Self.transientTypes.contains) {
            return .rejectedTransient
        }
        if Self.isExcluded(sourceBundleIdentifier, in: excludedBundleIdentifiers) {
            return .rejectedExcludedApp
        }
        if !captureEnabled {
            return .rejectedPaused
        }
        return .allow
    }

    // MARK: Liste d'exclusion

    /// Comparaison insensible à la casse et aux espaces de bordure.
    ///
    /// Un identifiant de bundle est théoriquement sensible à la casse, mais la liste est
    /// saisie ou complétée par l'utilisateur : refuser `com.Apple.Notes` parce qu'il a été
    /// noté autrement que `com.apple.Notes` reviendrait à enregistrer une copie qu'il croyait
    /// exclue. En cas de doute, on protège.
    private static func isExcluded(
        _ bundleIdentifier: String?,
        in excluded: [String]
    ) -> Bool {
        guard let identifier = normalized(bundleIdentifier), !identifier.isEmpty else {
            return false
        }
        return excluded.contains { normalized($0) == identifier }
    }

    private static func normalized(_ identifier: String?) -> String? {
        identifier?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased()
    }
}
