import Testing

@testable import CopyDraftCore

/// Type texte ordinaire, présent sur presque toute copie réelle : les marqueurs de
/// confidentialité l'accompagnent au lieu de le remplacer, d'où sa présence dans les cas.
private let plainText = "public.utf8-plain-text"

/// Appel de `decide` avec des valeurs nominales, pour que chaque test n'écrive que ce qu'il
/// met à l'épreuve.
private func decide(
    types: [String] = [plainText],
    from bundleIdentifier: String? = "com.apple.Notes",
    captureEnabled: Bool = true,
    excluded: [String] = []
) -> PrivacyDecision {
    PrivacyGate().decide(
        availableTypes: types,
        sourceBundleIdentifier: bundleIdentifier,
        captureEnabled: captureEnabled,
        excludedBundleIdentifiers: excluded
    )
}

@Suite("Filtre de confidentialité")
struct PrivacyGateTests {
    // MARK: Cas nominal

    @Test("Un texte ordinaire d'une application quelconque est accepté")
    func plainTextIsAllowed() {
        #expect(decide() == .allow)
    }

    @Test("Un presse-papiers sans aucun type annoncé est accepté")
    func noTypeIsAllowed() {
        #expect(decide(types: []) == .allow)
    }

    // MARK: Marqueurs confidentiels (FR-9)

    @Test("Le marqueur ConcealedType est rejeté")
    func concealedTypeIsRejected() {
        #expect(decide(types: ["org.nspasteboard.ConcealedType"]) == .rejectedConcealed)
        #expect(
            decide(types: ["org.nspasteboard.ConcealedType", plainText]) == .rejectedConcealed
        )
    }

    @Test("Le marqueur propriétaire 1Password est rejeté")
    func onePasswordTypeIsRejected() {
        #expect(decide(types: ["com.agilebits.onepassword"]) == .rejectedConcealed)
        #expect(decide(types: [plainText, "com.agilebits.onepassword"]) == .rejectedConcealed)
    }

    @Test("Le marqueur TransientType est rejeté")
    func transientTypeIsRejected() {
        #expect(decide(types: ["org.nspasteboard.TransientType"]) == .rejectedTransient)
        #expect(
            decide(types: ["org.nspasteboard.TransientType", plainText]) == .rejectedTransient
        )
    }

    @Test("Le marqueur AutoGeneratedType est rejeté")
    func autoGeneratedTypeIsRejected() {
        #expect(decide(types: ["org.nspasteboard.AutoGeneratedType"]) == .rejectedTransient)
        #expect(
            decide(types: [plainText, "org.nspasteboard.AutoGeneratedType"]) == .rejectedTransient
        )
    }

    /// Le rejet ne dépend d'aucun réglage : capture active, aucune exclusion, tout est au vert
    /// et pourtant rien ne passe. C'est l'exigence « non désactivable » de FR-9.
    @Test("Aucun réglage ne permet d'accepter un type toujours rejeté")
    func alwaysRejectedTypesIgnoreSettings() {
        for type in PrivacyGate.alwaysRejectedTypes {
            #expect(
                decide(types: [type, plainText], captureEnabled: true, excluded: []) != .allow,
                "le type \(type) a été accepté"
            )
        }
        #expect(PrivacyGate.alwaysRejectedTypes.count == 4)
    }

    // MARK: Liste d'exclusion (FR-11)

    @Test("Une application de la liste d'exclusion est ignorée")
    func excludedAppIsRejected() {
        #expect(
            decide(from: "com.apple.Terminal", excluded: ["com.apple.Terminal"])
                == .rejectedExcludedApp
        )
    }

    @Test("L'exclusion ne dépend pas de la casse saisie")
    func exclusionIsCaseInsensitive() {
        #expect(
            decide(from: "com.apple.Terminal", excluded: ["COM.APPLE.TERMINAL"])
                == .rejectedExcludedApp
        )
        #expect(
            decide(from: "COM.APPLE.Terminal", excluded: ["com.apple.terminal"])
                == .rejectedExcludedApp
        )
    }

    @Test("Une application absente de la liste passe")
    func unlistedAppIsAllowed() {
        #expect(decide(from: "com.apple.Safari", excluded: ["com.apple.Terminal"]) == .allow)
    }

    /// Identifiant partiel ou préfixe : l'exclusion est une égalité, jamais une inclusion,
    /// sinon exclure `com.apple.Mail` exclurait aussi `com.apple.MailDrop`.
    @Test("Un identifiant seulement préfixe d'un exclu n'est pas exclu")
    func prefixIsNotExcluded() {
        #expect(decide(from: "com.apple.MailDrop", excluded: ["com.apple.Mail"]) == .allow)
    }

    @Test("Une application source inconnue ne déclenche aucune exclusion")
    func missingBundleIdentifierIsAllowed() {
        #expect(decide(from: nil, excluded: ["com.apple.Terminal"]) == .allow)
        #expect(decide(from: "", excluded: [""]) == .allow)
    }

    // MARK: Pause (FR-10)

    @Test("En pause, rien n'est enregistré")
    func pauseRejects() {
        #expect(decide(captureEnabled: false) == .rejectedPaused)
    }

    // MARK: Priorité des raisons

    /// La raison rendue sert au diagnostic : quand tout s'applique à la fois, elle doit
    /// désigner la plus grave, dans l'ordre confidentiel > transitoire > exclue > pause.
    @Test("La raison la plus grave l'emporte quand plusieurs s'appliquent")
    func reasonPriority() {
        let everything = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            plainText,
        ]
        #expect(
            decide(
                types: everything, from: "com.apple.Terminal", captureEnabled: false,
                excluded: ["com.apple.Terminal"]
            ) == .rejectedConcealed
        )

        #expect(
            decide(
                types: ["org.nspasteboard.TransientType", plainText],
                from: "com.apple.Terminal", captureEnabled: false,
                excluded: ["com.apple.Terminal"]
            ) == .rejectedTransient
        )

        #expect(
            decide(from: "com.apple.Terminal", captureEnabled: false, excluded: ["com.apple.Terminal"])
                == .rejectedExcludedApp
        )
    }

    // MARK: Non-régression

    /// **Test de non-régression exigé par le PRD (FR-9, S-1.3) — à ne jamais supprimer.**
    ///
    /// Reproduit une copie réelle depuis un gestionnaire de mots de passe : le marqueur
    /// confidentiel accompagne un type texte parfaitement banal, la capture est active et
    /// l'application n'est pas exclue. Si ce test devient vert par accident — marqueur retiré
    /// de la liste, ordre des vérifications modifié — CopyDraft enregistre des mots de passe.
    @Test("Non-régression : une copie depuis un gestionnaire de mots de passe est refusée")
    func passwordManagerCopyIsNeverStored() {
        let decision = PrivacyGate().decide(
            availableTypes: ["org.nspasteboard.ConcealedType", "public.utf8-plain-text"],
            sourceBundleIdentifier: "com.agilebits.onepassword",
            captureEnabled: true,
            excludedBundleIdentifiers: []
        )

        #expect(decision == .rejectedConcealed)
        #expect(decision != .allow)
    }
}
